language: c

os: linux-ppc64le
dist: xenial

sudo: required

services: docker

env:
    matrix:
    - RUN_ON_CONTAINER=fedora-rawhide

script:
    - sudo docker build --pull -t ${RUN_ON_CONTAINER} -f ppc64-diag-ci/Dockerfile-${RUN_ON_CONTAINER} .
    - sudo docker run --privileged --volume $HOME/.ccache:/root/.ccache --volume `pwd`:/build --rm -t $RUN_ON_CONTAINER bash -c "./ppc64-diag-ci/build-${RUN_ON_CONTAINER}.sh";
